package com.ridego.enums;

public enum NotificationType {
    REGISTRATION,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAILED,
    PICKUP_REMINDER,
    RETURN_REMINDER,
    REFUND_INITIATED,
    MAINTENANCE_UPDATE
}
